# Generated by Django 5.1.1 on 2024-10-24 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_projects_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='technologies',
            field=models.CharField(default='', max_length=250),
        ),
    ]
