# Generated by Django 5.1.1 on 2024-11-01 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_projects_technologies'),
    ]

    operations = [
        migrations.AddField(
            model_name='engineer',
            name='inspo',
            field=models.TextField(default='Inspired by Tony Stark.', max_length=500),
        ),
    ]
