# Generated by Django 5.1.1 on 2024-11-01 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_engineer_inspo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engineer',
            name='inspo',
            field=models.TextField(max_length=500),
        ),
    ]
